/* Local pilot feedback. One editable vote per article and release in this browser. */
const KnowledgeFeedback=(()=>{
 const key='flightdeck-feedback-v1';
 const reasons=['Wrong procedure','Missing information','Unclear instructions','PDF/page issue'];
 function rows(){try{const a=JSON.parse(localStorage.getItem(key)||'[]');return Array.isArray(a)?a.filter(x=>x&&typeof x.key==='string'&&['up','down'].includes(x.rating)):[]}catch{return []}}
 function context(){const p=activeProcedure();return p&&knowledgePack&&KnowledgeCore.readable(p)?{key:JSON.stringify([knowledgePack.release,knowledgePack.document?.sha256||'',p.id]),articleId:p.id,articleTitle:p.heading,release:knowledgePack.release,documentHash:knowledgePack.document?.sha256||''}:null}
 function save(rating,reason='',comment=''){const c=context();if(!c)return false;const all=rows().filter(x=>x.key!==c.key);all.push({...c,rating,reason:rating==='down'&&reasons.includes(reason)?reason:'',comment:rating==='down'?String(comment).trim().slice(0,500):'',updatedAt:new Date().toISOString()});try{localStorage.setItem(key,JSON.stringify(all));return true}catch{toast('Rating could not be saved. Browser storage may be full or disabled.');return false}}
 function markup(){const c=context();if(!c)return '';const vote=rows().find(x=>x.key===c.key);return `<span class="knowledge-feedback" role="group" aria-label="Was this procedure helpful?"><span>Helpful?</span><button data-rating="up" aria-label="Helpful" aria-pressed="${vote?.rating==='up'}" title="Helpful">👍</button><button data-rating="down" aria-label="Not helpful" aria-pressed="${vote?.rating==='down'}" title="Not helpful">👎</button>${vote?'<small>Saved</small>':''}</span>`}
 const originalToolbar=readerToolbar;readerToolbar=function(p){return originalToolbar(p).replace('<button data-source-details>',markup()+'<button data-source-details>')};
 const dialog=document.createElement('dialog');dialog.id='feedbackReason';dialog.dataset.usageMode='setup';document.body.appendChild(dialog);let targetKey='';
 function refresh(){document.querySelectorAll('.knowledge-feedback').forEach(el=>{el.outerHTML=markup()})}
 document.addEventListener('click',e=>{const b=e.target.closest('[data-rating]');if(!b||!save(b.dataset.rating))return;refresh();if(b.dataset.rating==='down'){targetKey=context()?.key;dialog.innerHTML='<h2>What could be better?</h2><p>Optional. Your rating is already saved in this browser.</p>'+reasons.map(x=>`<button data-feedback-reason="${x}">${x}</button>`).join(' ')+'<label for="feedbackComment">What would help? (optional)</label><textarea id="feedbackComment" maxlength="500" rows="3" placeholder="Do not include customer or loan information."></textarea><p><button data-feedback-save>Save details</button> <button data-feedback-close>Done / skip details</button></p>';dialog.dataset.reason='';dialog.showModal()}else toast('Helpful rating saved in this browser.');});
 dialog.addEventListener('click',e=>{const reason=e.target.closest('[data-feedback-reason]');if(reason&&context()?.key===targetKey){dialog.dataset.reason=reason.dataset.feedbackReason;dialog.querySelectorAll('[data-feedback-reason]').forEach(b=>b.setAttribute('aria-pressed',String(b===reason)));save('down',dialog.dataset.reason)}if(e.target.closest('[data-feedback-save]')&&context()?.key===targetKey){if(save('down',dialog.dataset.reason,document.getElementById('feedbackComment').value)){dialog.close();refresh();toast('Feedback details saved.')}}if(e.target.closest('[data-feedback-close]'))dialog.close()});

 const style=document.createElement('style');style.textContent='.knowledge-feedback{display:inline-flex;align-items:center;gap:4px;margin-right:10px;font-size:13px}.knowledge-feedback button{padding:4px 7px;min-height:30px}.knowledge-feedback button[aria-pressed="true"]{outline:2px solid var(--accent,#2457a6)}.knowledge-feedback small{font-size:11px}.reader-source-actions{display:flex;align-items:center;flex-wrap:wrap;gap:4px}';document.head.appendChild(style);
 const exportButton=document.createElement('button');exportButton.textContent='Export article feedback';document.getElementById('returnAgent').after(exportButton);exportButton.onclick=()=>{if(!adminDemoUnlocked)return;const all=rows();if(!all.length){toast('No article ratings saved in this browser yet.');return}const cols=['articleId','articleTitle','release','documentHash','rating','reason','comment','updatedAt'];const cell=v=>'"'+String(v??'').replace(/^[=+@-]/,"'$&").replace(/"/g,'""')+'"';const csv='\uFEFF'+[cols.join(','),...all.map(r=>cols.map(c=>cell(r[c])).join(','))].join('\r\n');const url=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download='FlightDeck-article-feedback-'+new Date().toISOString().slice(0,10)+'.csv';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)};
 const viewButton=document.createElement('button');viewButton.textContent='View article feedback';exportButton.before(viewButton);viewButton.onclick=()=>{if(!adminDemoUnlocked)return;const all=rows();const report=document.createElement('dialog');report.style.width='min(1000px,94vw)';report.dataset.usageMode='setup';report.innerHTML='<h2>Article feedback — this browser</h2><p>One editable rating per article and release in this browser. These are not team-wide counts. Export each pilot browser separately.</p>'+(!all.length?'<p>No ratings yet.</p>':'<div style="max-height:60vh;overflow:auto"><table><thead><tr><th>Article / release</th><th>Rating</th><th>Reason / comment</th></tr></thead><tbody>'+all.map(x=>'<tr><td>'+kEscape(x.articleTitle)+'<br><small>'+kEscape(x.articleId+' · '+x.release)+'</small></td><td>'+ (x.rating==='up'?'Helpful':'Not helpful')+'</td><td>'+kEscape(x.reason||'')+'<p style="white-space:pre-wrap">'+kEscape(x.comment||'')+'</p></td></tr>').join('')+'</tbody></table></div>')+'<button data-close-feedback-report>Close</button>';document.body.appendChild(report);report.querySelector('[data-close-feedback-report]').onclick=()=>report.close();report.addEventListener('close',()=>report.remove());report.showModal()};
 return {rows,save,context,markup};
})();

// Knowledge browsing also returns agents to the mapped procedure workspace.
kProcedure=function(p){return p?`<h3>${kEscape(p.heading)}</h3><p>${kEscape(p.id)} · ${kEscape(kReviewLabel(p))}</p>${KnowledgeCore.readable(p)?`<button data-open-mapped-procedure="${kEscape(p.id)}">View procedure</button>`:'<p>Procedure unavailable in this release.</p>'}`:'<p>Select a procedure.</p>'};
document.addEventListener('click',e=>{const b=e.target.closest('[data-open-mapped-procedure]');if(b){kEl('knowledgeDialog').close();navigateReader(b.dataset.openMappedProcedure)}});
