/* v2.28: streamlined review with explicit source and placement states. */
let comparisonPdfUrl='',comparisonPdfFile=null,attachedPreviousPdf=null,attachedPreviousHash='';
function previousSourceUrl(){const f=previousPdfFile||(attachedPreviousHash===baseline?.document?.sha256?attachedPreviousPdf:null);if(!f||!baseline?.document)return '';if(comparisonPdfFile!==f){if(comparisonPdfUrl)URL.revokeObjectURL(comparisonPdfUrl);comparisonPdfUrl=URL.createObjectURL(f);comparisonPdfFile=f}return comparisonPdfUrl}
function reviewSourceIssue(m,r){return !!r&&(r.status!=='matched'||matchingFlags(m,r).length>0)}
const baseVisibleReview=reviewVisibleMappings;
reviewVisibleMappings=function(){const mode=byId('reviewFilter').value,q=byId('reviewSearch').value.trim().toLowerCase();if(!['issues','changed'].includes(mode))return baseVisibleReview();return mappings.filter(m=>{const r=results[m.id];return (!q||(m.id+' '+m.heading+' '+(m.displayName||'')).toLowerCase().includes(q))&&(mode==='issues'?reviewSourceIssue(m,r):['changed','visual-change','visual-review'].includes(r?.kind))})};
for(const [value,label] of [['issues','Source issues'],['changed','Changed procedures']]){const o=document.createElement('option');o.value=value;o.textContent=label;byId('reviewFilter').appendChild(o)}
function reviewQueue(){return reviewVisibleMappings().map(m=>m.id)}
function advanceReview(queue,from){const at=queue.indexOf(from),ordered=[...queue.slice(at+1),...queue.slice(0,at)];const visible=new Set(reviewQueue());const next=ordered.find(id=>visible.has(id)&&results[id]&&!results[id].decision);if(next){active=next;renderAll();byId('review').scrollIntoView({block:'start'})}else{renderAll();byId('progressText').textContent='No other unresolved subjects in this filtered queue. Change the filter to continue.'}}
byId('nextReview').onclick=()=>{if(!busy)advanceReview(reviewQueue(),active)};
function foldReviewRange(first,last,title,open=false){if(!first||!last||first.parentNode!==last.parentNode)return;const d=document.createElement('details');d.open=open;const summary=document.createElement('summary');summary.textContent=title;d.appendChild(summary);first.before(d);let node=first;while(node){const next=node.nextSibling;d.appendChild(node);if(node===last)break;node=next}return d}
function beforeLabel(id){return document.querySelector('label[for="'+id+'"]')}
const polishReviewBase=renderReview;
renderReview=function(){polishReviewBase();const m=mappings.find(x=>x.id===active),r=results[active];if(!m||!r)return;const host=byId('review');
 // Always expose source and placement as independent states.
 const status=document.createElement('p');status.className='review-status-line';status.textContent='Source: '+(r.decision==='reviewed'?'Reviewed':reviewSourceIssue(m,r)?'Needs correction':'Matched')+'  ·  Placement: '+(NavigationGroups.category(m)==='Needs placement'?'Needs placement':'Assigned — '+NavigationGroups.category(m));host.querySelector('h2').parentElement.after(status);
 const currentLink=Array.from(host.querySelectorAll('a')).find(a=>a.textContent==='Open original PDF at this section');if(currentLink){currentLink.textContent=baseline?'View updated PDF':'View current PDF';const prev=previousSourceUrl();if(r.old?.start&&prev){const a=document.createElement('a');a.className='button';a.textContent='View previous PDF';a.href=prev+'#page='+r.old.start;a.target='_blank';a.rel='noopener noreferrer';currentLink.before(a,document.createTextNode(' '))}}
 const sourceNote=document.createElement('p');sourceNote.className='small';sourceNote.textContent=!baseline?'First import — no previous version.':!r.old?.start?'No matched procedure in the previous version.':!previousSourceUrl()?'Previous PDF is not attached. The previous knowledge pack supplies comparison text only.':'Previous and updated links use their own physical page ranges.';status.after(sourceNote);
 if(baseline?.document?.sha256&&!previousSourceUrl()){const label=document.createElement('label');label.textContent='Attach matching previous PDF (optional)';const input=document.createElement('input');input.type='file';input.accept='.pdf,application/pdf';label.appendChild(input);sourceNote.after(label);input.onchange=async()=>{const f=input.files[0],expected=baseline.document.sha256;if(!f)return;try{if(f.size>150000000)throw Error('PDF exceeds 150 MB.');const hash=Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',await f.arrayBuffer())),b=>b.toString(16).padStart(2,'0')).join('');if(hash!==expected||baseline?.document?.sha256!==expected)throw Error('This PDF does not match the previous knowledge pack.');attachedPreviousPdf=f;attachedPreviousHash=hash;error('');renderReview()}catch(e){input.value='';error(e.message)}};}

 if(!currentLink&&r.old?.start&&previousSourceUrl()){const a=document.createElement('a');a.className='button';a.textContent='View previous PDF';a.href=previousSourceUrl()+'#page='+r.old.start;a.target='_blank';a.rel='noopener noreferrer';sourceNote.after(a)}
 if(!r.start){sourceNote.append(' No current matched section; correct the mapping or mark unavailable.');}
 // Navigation preferences remain available without dominating verification.
 const assist=byId('mappingAssist');const short=byId('subjectShortName'),label=beforeLabel('subjectShortName');if(short&&label){const d=foldReviewRange(label,short,'Agent label: '+(m.displayName||m.heading)+' — Edit');}
 foldReviewRange(beforeLabel('subjectNeed'),byId('subjectBrowserSection')?.nextElementSibling?.nextElementSibling,'Navigation details');
 // The home controls sit between need and browser fields; move them into their own section.
 const home=beforeLabel('subjectHome'),order=byId('subjectHomeOrder');const homeEnd=order?.nextElementSibling;const quick=foldReviewRange(home,homeEnd,'Quick access settings');
 if(quick){const featured=byId('subjectFeatured')?.parentElement;if(featured)quick.appendChild(featured);const updateOrder=()=>{const show=byId('subjectHome').value==='show';order.hidden=!show;beforeLabel('subjectHomeOrder').hidden=!show};byId('subjectHome').addEventListener('change',updateOrder);updateOrder();assist.appendChild(quick)}
 foldReviewRange(beforeLabel('subjectSearchTerms'),byId('subjectSearchTerms'),'Optional search phrases');
 const format=byId('formatEditor'),answer=byId('summary');if(format&&answer){const authored=document.createElement('details');authored.innerHTML='<summary>Optional authored guidance</summary>';format.before(authored);authored.appendChild(format);const answerLabel=beforeLabel('summary');if(answerLabel)authored.appendChild(answerLabel);const following=answer.nextElementSibling;authored.appendChild(answer);if(following?.tagName==='DETAILS')authored.appendChild(following);const hint=following?.tagName==='P'?following:authored.lastElementChild?.nextElementSibling;if(hint?.tagName==='P')authored.appendChild(hint)}
 const compare=Array.from(host.querySelectorAll('details')).find(d=>d.querySelector('summary')?.textContent==='Compare extracted text');if(compare&&['changed','visual-change','visual-review'].includes(r.kind)){compare.open=true;status.after(compare)}
 const resolve=Array.from(host.querySelectorAll('details')).find(d=>d.querySelector('summary')?.textContent==='Resolve heading or page range');if(resolve)resolve.open=reviewSourceIssue(m,r);
 const suggestionButton=byId('useMappingSuggestion');if(suggestionButton){const use=suggestionButton.onclick;suggestionButton.onclick=()=>{use();renderReview()}}
 const approve=byId('approve'),approveAction=approve.onclick;approve.onclick=()=>{const queue=reviewQueue(),id=active;if(!byId('reviewCheck').checked){approveAction();return}const previousReviewedAt=results[id]?.reviewedAt;approveAction();if(results[id]?.decision==='reviewed'&&results[id]?.reviewedAt!==previousReviewedAt)advanceReview(queue,id)};
 const skip=document.createElement('button');skip.textContent='Skip for now';skip.onclick=()=>advanceReview(reviewQueue(),active);approve.after(skip);
 const remove=byId('removeSubject');const more=document.createElement('details');more.innerHTML='<summary>More actions</summary>';remove.before(more);more.appendChild(remove);
 // Any placement edit is retained in a draft and updates the status immediately.
 for(const id of ['subjectNavCategory','subjectShortName','subjectSearchTerms','subjectFeatured'])byId(id)?.addEventListener('change',()=>{markDraftDirty();refreshDemoControls();status.textContent='Source: '+(r.decision==='reviewed'?'Reviewed':reviewSourceIssue(m,r)?'Needs correction':'Matched')+'  ·  Placement: '+(NavigationGroups.category(m)==='Needs placement'?'Needs placement':'Assigned — '+NavigationGroups.category(m))});
};
const reviewStyle=document.createElement('style');reviewStyle.textContent='#review details{margin:10px 0;padding:10px;border:1px solid #ccd4df;border-radius:8px}#review summary{cursor:pointer;font-weight:600}#review details details{background:transparent}.review-status-line{font-weight:600}#review .controls{align-items:center;flex-wrap:wrap}';document.head.appendChild(reviewStyle);
