const {JSDOM}=require('/tmp/flightdeck-dom/node_modules/jsdom');
const fs=require('fs'),vm=require('vm'),assert=require('assert/strict'),crypto=require('crypto');
function load(path){const html=fs.readFileSync(path,'utf8'),dom=new JSDOM(html,{url:'https://pilot.test/index.html',runScripts:'outside-only',pretendToBeVisual:true});const w=dom.window;Object.assign(w,{TextEncoder,TextDecoder,structuredClone,Blob,File,confirm:()=>true,alert:()=>{},ResizeObserver:class{observe(){}disconnect(){}}});Object.defineProperty(w.crypto,'subtle',{value:crypto.webcrypto.subtle});w.URL.createObjectURL=()=> 'blob:test-'+Math.random();w.URL.revokeObjectURL=()=>{};w.HTMLElement.prototype.scrollIntoView=function(){};w.HTMLDialogElement.prototype.showModal=function(){this.open=true};w.HTMLDialogElement.prototype.close=function(){this.open=false;this.dispatchEvent(new w.Event('close'))};w.HTMLCanvasElement.prototype.getContext=()=>null;const context=dom.getInternalVMContext();vm.runInContext(html.match(/<script>\s*([\s\S]*?)<\/script>/)[1],context);return {w,run:s=>vm.runInContext(s,context),close:()=>w.close()}}
(async()=>{const ad=load('pilot-package/knowledge-admin.html'),d=ad.w.document;const pack=JSON.parse(fs.readFileSync('pilot-package/sample-knowledge-v1.json'));ad.w.pack=pack;
ad.run('baseline=pack;mappings=pack.procedures.map(mappingFromProcedure);editExistingPack();');
assert(d.querySelector('#review .review-status-line').textContent.includes('Source: Reviewed'));
for(const label of ['Navigation details','Quick access settings','Optional authored guidance','More actions'])assert([...d.querySelectorAll('#review summary')].some(x=>x.textContent===label),label);
assert.equal(d.querySelector('#subjectHomeOrder').hidden,true);
assert(d.querySelector('#subjectNeed').closest('details').querySelector('summary').textContent==='Navigation details');
assert(d.querySelector('#subjectHome').closest('details').querySelector('summary').textContent==='Quick access settings');
assert(d.querySelector('#subjectSearchTerms').closest('details').querySelector('summary').textContent==='Optional search phrases');
assert(d.querySelector('#summary').closest('details').querySelector('summary').textContent==='Optional authored guidance');
// Approve and skip preserve queue and query; unchecked approval must not advance.
ad.run('mappings=mappings.slice(0,3);for(const m of mappings){m.category="Escrow";results[m.id].decision=null;results[m.id].presentation=null;}active=mappings[0].id;renderAll()');
d.querySelector('#reviewFilter').value='pending';d.querySelector('#reviewSearch').value='';ad.run('renderAll()');const first=ad.run('active');d.querySelector('#approve').click();assert.equal(ad.run('active'),first);assert.equal(ad.run('results[active].decision'),null);d.querySelector('#reviewCheck').checked=true;d.querySelector('#approve').click();assert.notEqual(ad.run('active'),first);assert.equal(d.querySelector('#reviewFilter').value,'pending');assert.equal(ad.run(`results[${JSON.stringify(first)}].decision`),'reviewed');const second=ad.run('active');[...d.querySelectorAll('button')].find(b=>b.textContent==='Skip for now').click();assert.notEqual(ad.run('active'),second);assert.equal(ad.run(`results[${JSON.stringify(second)}].decision`),null);
// Paired source links carry different page destinations.
ad.run('active=mappings[0].id;previousPdfFile=new File(["pdf"],"previous.pdf");pdfUrl="blob:updated";results[active].old={start:2,end:3};results[active].start=5;results[active].end=6;renderReview()');const links=[...d.querySelectorAll('#review a')];assert(links.some(a=>a.textContent==='View previous PDF'&&a.href.endsWith('#page=2')));assert(links.some(a=>a.textContent==='View updated PDF'&&a.href==='blob:updated#page=5'));
// Source issues and visual changes can be queued separately.
ad.run('results[mappings[1].id].status="ambiguous";results[mappings[2].id].kind="visual-change"');d.querySelector('#reviewFilter').value='issues';assert(ad.run('reviewVisibleMappings().some(m=>results[m.id].status==="ambiguous")'));d.querySelector('#reviewFilter').value='changed';assert(ad.run('reviewVisibleMappings().some(m=>results[m.id].kind==="visual-change")'));ad.close();
const agent=load('pilot-package/index.html'),a=agent.w.document;await agent.run('deviceStartup');agent.w.pack=pack;agent.run('kLoad(pack);LocalPdf.paint=async()=>{};navigateReader("ESC-001");knowledgePdfUrl="blob:test";render()');assert(!a.querySelector('#content').textContent.includes('Open full manual'));assert(a.querySelector('[data-rating="down"]'));a.querySelector('[data-rating="down"]').click();assert.equal(agent.run('KnowledgeFeedback.rows()[0].rating'),'down');a.querySelector('[data-feedback-reason="PDF/page issue"]').click();a.querySelector('#feedbackComment').value='Page ends before the last step <script>bad</script>';a.querySelector('[data-feedback-save]').click();assert.equal(agent.run('KnowledgeFeedback.rows()[0].reason'),'PDF/page issue');assert(agent.run('KnowledgeFeedback.rows()[0].comment.includes("last step")'));agent.run('adminDemoUnlocked=true');[...a.querySelectorAll('button')].find(b=>b.textContent==='View article feedback').click();assert(a.querySelector('dialog[open] table').textContent.includes('<script>bad</script>'));assert.equal(a.querySelector('dialog[open] table script'),null);a.querySelector('[data-close-feedback-report]').click();a.querySelector('[data-rating="up"]').click();assert.equal(agent.run('KnowledgeFeedback.rows().length'),1);assert.equal(agent.run('KnowledgeFeedback.rows()[0].comment'),'');agent.run('knowledgePack.release="Next release";KnowledgeFeedback.save("down","Unclear instructions","Different release")');assert.equal(agent.run('KnowledgeFeedback.rows().length'),2);assert.equal(agent.run('KnowledgeFeedback.save("down","", "x".repeat(700));KnowledgeFeedback.rows().at(-1).comment.length'),500);const previousRows=agent.run('JSON.stringify(KnowledgeFeedback.rows())');agent.w.Storage.prototype.setItem=function(){throw Error('quota')};assert.equal(agent.run('KnowledgeFeedback.save("up")'),false);assert.equal(agent.run('JSON.stringify(KnowledgeFeedback.rows())'),previousRows);agent.close();console.log('PASS: DOM controls, collapsed groups, approval/skip queues, source links, filters, rating persistence/update/release separation, comments, escaped Admin report.');})().catch(e=>{console.error(e);process.exit(1)});
